# -*- coding: utf-8 -*-
"""sam2_on_kitti.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1J3WU3MjFeCgMN8s7Sg5AIIWxrruMDU_v
"""

# !pip install fiftyone
# !pip install sam2

import torch
import torchvision
import fiftyone as fo
import fiftyone.zoo as foz
import fiftyone.brain as fob
from fiftyone import ViewField as F

import os, sys
import cv2
import matplotlib.pyplot as plt
from zipfile import ZipFile

import numpy as np
import PIL

dataset = foz.load_zoo_dataset( "kitti",
                               split="test",
                               max_samples = 500,
                               dataset_name="kitti",
                               only_matching = True
                               )

dataset

dataset.head(1)

session = fo.launch_app(dataset)

session.freeze()

# !pip install sam2
model = foz.load_zoo_model("segment-anything-2-hiera-base-plus-image-torch")

predictions_view = dataset.take(50)
session.view = predictions_view

session.freeze()

device="cpu"
if torch.cuda.is_available():
    device = torch.device("cuda")
print(f"using device: {device}")

predictions_view.apply_model(
   model=model,
   label_field="predictions",
    # confidence_thresh=0.7,
    store_logits=False,
    # batch_size=16,
    # num_workers=1,
   skip_failures=True,
    # output_dir="path",
    progress=True,

)

results = predictions_view.evaluate_detections( "predictions",
                                               gt_field="ground_truth",
                                               eval_key="eval",
                                               use_masks = True
)

# Convert to evaluation patches
eval_patches = predictions_view.to_evaluation_patches("eval")
print(eval_patches)

print(eval_patches.count_values("type"))

session.view = eval_patches

session.freeze



